version: "3"

services:
  app:
    build: .
    image: gorokhismyname/devops-example-app:v2

  caddy:
    build:
      context: .
      dockerfile: services/caddy/Dockerfile
    image: gorokhismyname/devops-example-caddy:v2
