---

- hosts: all
  gather_facts: no
  become: true
  tasks:

    # - community.docker.docker_network:
    #     name: devops-example

    - community.docker.docker_container:
        name: app
        image: "gorokhismyname/devops-example-app:{{ version }}"
        # Подключаем супервизор
        # Если контейнер остановится, например, из-за ошибок
        # супервизор докера его перезапустить
        restart_policy: always
        state: started
        networks:
          - name: devops-example
        ports:
          - 3000:3000
        env: # Настраиваем
          NODE_ENV: production

    - community.docker.docker_container:
        name: caddy
        image: "gorokhismyname/devops-example-caddy:{{ version }}"
        restart_policy: always
        state: started
        networks:
          - name: devops-example
        ports:
          - 8080:80
          - 8443:443
