---

- hosts: all
  gather_facts: no
  become: true
  tasks:

    - apt:
        name: python3-pip
        update_cache: yes
        cache_valid_time: 604800 # 1 week

    - pip:
        name: docker

    - docker_image:
        name: hello-world
        source: pull

    - docker_container:
        name: hello-world
        state: started